CREATE TABLE IF NOT EXISTS accounts (
    id UUID PRIMARY KEY,
    owner TEXT NOT NULL,
    balance BIGINT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1
);